providers = ["node"]

[phases.setup]
aptPkgs = [
    "wget",
    "gnupg",
    "libnss3",
    "libatk1.0-0", 
    "libatk-bridge2.0-0",
    "libcups2",
    "libgbm1",
    "libasound2t64",
    "libpangocairo-1.0-0",
    "libxss1",
    "libgtk-3-0",
    "libxshmfence1",
    "libglu1",
    "libxrandr2",
    "libxcomposite1",
    "libxdamage1",
    "libxfixes3",
    "ca-certificates",
    "fonts-liberation",
    "libappindicator3-1",
    "libc6",
    "libcairo-gobject2",
    "libdbus-1-3",
    "libdrm2",
    "libgtk-3-0",
    "libnspr4",
    "libnss3",
    "libx11-6",
    "libxcb1",
    "libxext6",
    "libxss1",
    "libxtst6",
    "lsb-release",
    "xdg-utils"
]
cmds = [
    "wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -",
    "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google-chrome.list",
    "apt-get update",
    "apt-get install -y google-chrome-stable"
]

[phases.install]
cmds = ["npm ci --prefer-offline --no-audit --no-fund"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/google-chrome-stable"